#配置数据源
spring:
  datasource:
    url: jdbc:mysql:///yjh
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#    配置Mybatis的配置文件路径
mybatis:
  mapper-locations: classpath:Mapper/YjhMapper.xml #Mapper的映射文件路径
  type-aliases-package: package com.example.demo.Pojo;
#  config-location: #这里是用来指定mybatis的核心配置文件的
